Always try to run make
* If no makefile is found, run make command in current directory.
* New test for `makefile --version`.
* Cleanup: don't cd to `build/.`, for example.
* Better debugging support.
* Better test output.

diff --git a/tests/test b/tests/test
--- a/tests/test
+++ b/tests/test
@@ -1,22 +1,49 @@
 #!/bin/bash
 
-fail=0
+test_count=0
+fail_count=0
+
+ok() {
+    echo OK
+    test_count=$((${test_count} + 1))
+}
+
+fail() {
+    exp="$1"
+    got="$2"
+    echo FAIL
+    if [ -n "${exp}" -a -n "${got}" ]; then
+        echo expected: ${exp}, got: ${got}
+    fi
+    test_count=$((${test_count} + 1))
+    fail_count=$((${fail_count} + 1))
+}
 
 oosmake="$(pwd)/../oosmake"
+
 for i in case-*; do
     echo -n "$i… "
     cd "$i"
     got=$(. prep && "${oosmake}")
     exp=$(echo -n $(readlink -f $(pwd)) && cat expect)
     if [ "${got}" == "${exp}" ]; then
-        echo OK
+        ok
     else
-        echo FAIL
-        echo expected: ${exp}, got: ${got}
-        fail=1
+        fail "${exp}" "${got}"
     fi
     cd ..
 done
 
-exit ${fail}
+echo -n '$(oosmake --version)… '
+if "${oosmake}" --version >/dev/null 2>&1; then
+    ok
+else
+    fail
+fi
 
+if [ 0 != ${fail_count} ]; then
+    echo "*** ${fail_count} of ${test_count} tests failed"
+    exit 1
+fi
+
+echo "ALL PASS"
